import { Linkedin } from "lucide-react";

export const siteConfig = {  name: "Portafolio de Alfonso",
  authorName: "Alfonso Ángel Mosquera A.",
  username: "foonroot01",  description:
    "Ingeniero TI con experiencia en soporte técnico, redes, sistemas y ciberseguridad. Buscando nuevos retos.",
  url: "https://alfonsom.vercel.app",
  links: {
    Linkedin: "www.linkedin.com/in/alfonso-ángel-mosquera-a-4a919b341",
    github: "https://github.com/fonroot01",
  },
  ogImage: "/alfonsoimage.jpg",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords:[
    "Alfonso Angel Mosquera Alvzarez",
    "Ingeniero de Sistemas",
    "Soporte Técnico",
    "Ciberseguridad",
    "Administrador de Sistemas",
    "Python Developer",
    "Linux",
    "Next.js template",
    "Windows",
    "Redes",
    "Virtualización",
    "GitHub",
    "Portafolio de Alfonso",
    "Portafolio de Alfonso Ángel Mosquera A.",
    "Portfolio de Alfonso Mosquera",
    "Portafolio profesional",
    "technical support",
    "system administrator",
    "Automatizacion de tareas",
    "SQL Server",
    "Ciberseguridad portfolio",
    "Portafolio de Ciberseguridad",
    "Portafolio con modo oscuro",
  ],
};
