import { Linkedin } from "lucide-react";

export const siteConfig = {  name: "Portafolio de Alfonso",
  authorName: "Alfonso Ángel Mosquera A.",
  username: "foonroot01",  description:
    "Ingeniero TI con experiencia en soporte técnico, redes, sistemas y ciberseguridad. Buscando nuevos retos.",
  url: "https://alfonsom.vercel.app",
  links: {
    Linkedin: "www.linkedin.com/in/alfonso-ángel-mosquera-a-4a919b341",
    github: "https://github.com/fonroot01",
  },
  ogImage: "/alfonsoimage.jpg",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords:[
    "Alfonso Mosquera",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
